name: Use Template

on:
  create:

permissions:
  contents: write

jobs:
  clone:
    if: github.event.repository.name != 'skeleton.go'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: replace with new repository name
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          REPO_OWNER: ${{ github.event.repository.owner.login }}
        run: |
          find ./ -type f \
            -not -path "./.github/workflows/*" \
            -not -path "./.git/*" \
            -exec sed -i -e 's/skeleton.go/${{ env.REPO_NAME }}/g' \
            -e 's/suft/${{ env.REPO_OWNER }}/g' {} +
      - name: commit changes
        env:
          ACTOR: ${{ github.actor }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          git config --global user.email "${{ env.ACTOR }}@users.noreply.github.com"
          git config --global user.name "${{ env.ACTOR }}"
          git add .
          git commit -m "feat: intialize new repo"
          git push origin ${{ env.REF_NAME }}
