name: Use Template

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  use-template:
    if: github.event.repository.name != 'skeleton.go'
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      ACTOR: ${{ github.actor }}
    steps:
      - uses: actions/checkout@v4

      - name: Replace With New Repository Name
        env:
          REPO_OWNER: ${{ github.event.repository.owner.login }}
        run: |
          find ./ -type f \
            -not -path "./.github/workflows/*" \
            -not -path "./.git/*" \
            -exec sed -i -e 's/skeleton.go/${{ env.REPO_NAME }}/g' \
            -e 's/suft/${{ env.REPO_OWNER }}/g' {} +

      - name: Delete This Workflow File
        run: |
          rm -f .github/workflows/use-template.yml

      - name: Get User Email
        id: user_email
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          EMAIL=$(gh api users/${{ env.ACTOR }} --jq '.email')
          if [[ -z "$EMAIL" || "$EMAIL" == "null" ]]; then
            EMAIL="${{ env.ACTOR }}@users.noreply.github.com"
          fi
          echo "EMAIL=$EMAIL" >> $GITHUB_ENV

      - name: Commit Changes
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          git config --global user.email "$EMAIL"
          git config --global user.name "${{ env.ACTOR }}"
          git add .
          git commit -m "chore: initialize repository ${{ env.REPO_NAME}}"
          git push origin ${{ env.REF_NAME }}
